### ISSUE TITLE
Document node >= 12 requirement for using cache-restore, cache-save

### ISSUE THREAD

**Issue by brettdh** [ktmud/cached-dependencies#69]
The default for `actions/setup-node@v1` is node 10, which does not work with this action. I saw that the action itself is configured to run using node 12, but the `cache-restore` and `cache-save` scripts just use the `node` that's on `PATH`, which causes a silent failure to restore/save the cache:

```
  (node:6173) UnhandledPromiseRejectionWarning: TypeError: Object.fromEntries is not a function
      at Object.<anonymous> (/Users/runner/work/_actions/ktmud/cached-dependencies/v1/dist/scripts/cache/index.js:5812:39)
      at Generator.next (<anonymous>)
      at /Users/runner/work/_actions/ktmud/cached-dependencies/v1/dist/scripts/cache/index.js:5763:71
      at new Promise (<anonymous>)
      at module.exports.935.__awaiter (/Users/runner/work/_actions/ktmud/cached-dependencies/v1/dist/scripts/cache/index.js:5759:12)
      at Object.applyInputs (/Users/runner/work/_actions/ktmud/cached-dependencies/v1/dist/scripts/cache/index.js:5811:12)
      at Object.save (/Users/runner/work/_actions/ktmud/cached-dependencies/v1/dist/scripts/cache/index.js:5180:25)
      at Object.<anonymous> (/Users/runner/work/_actions/ktmud/cached-dependencies/v1/dist/scripts/cache/index.js:5204:46)
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/work/_actions/ktmud/cached-dependencies/v1/dist/scripts/cache/index.js:5048:58)
```

If it's possible to make the `cache-restore` and `cache-save` scripts use node 12, that'd be great. If not, it would be good to at least document the requirement to run `setup-node` with `node-version: '12'`.

**Comment by ktmud** [comment]
Or we can add support for node 10 by updating the build script to `ncc build --target es2015`.

Do you mind testing it out and making a PR if it works?

**Comment by brettdh** [comment]
Sure, I'll try to take a look soon.

**Comment by brettdh** [comment]
Results: `Object.fromEntries` requires `es2019`, which is [not available in Node 10](https://node.green/#ES2019-features--Object-fromEntries). Interestingly, `ncc` will build under Node 10 with `--target es2019`, but this doesn't affect the tests, two of which fail:

```
  ● cache runner › should apply inputs and restore cache                         
                                                                                                  
    TypeError: Object.fromEntries is not a function                              
                                                 
      45 |   runner: () => Promise<void>, 
      46 | ): Promise<any> {
    > 47 |   const originalInputs: Inputs = Object.fromEntries(
         |                                         ^
      48 |     Object.keys(inputs).map(name => [
      49 |       name,
      50 |       EnvVariableNames.has(name) ? process.env[name] : core.getInput(name),
                                                 
      at Object.<anonymous> (src/utils/inputs.ts:47:41)
      at src/utils/inputs.ts:2217:41
      at __awaiter (src/utils/inputs.ts:2160:10)
      at Object.applyInputs (src/utils/inputs.ts:2323:10)
      at Object.restore (src/cache/index.ts:104:12)                             
      at Object.<anonymous> (src/cache/index.ts:137:13)
      at fulfilled (src/cache/index.ts:3987:24)

  ● cache runner › should run saveCache                                                           
                                                 
    TypeError: Object.fromEntries is not a function
                                                                                                  
      45 |   runner: () => Promise<void>,                                                         
      46 | ): Promise<any> {                                                                      
    > 47 |   const originalInputs: Inputs = Object.fromEntries(
         |                                         ^
      48 |     Object.keys(inputs).map(name => [
      49 |       name,                                                                            
      50 |       EnvVariableNames.has(name) ? process.env[name] : core.getInput(name),
                                                 
      at Object.<anonymous> (src/utils/inputs.ts:47:41)        
      at src/utils/inputs.ts:2217:41                                                                                                                                                                 
      at __awaiter (src/utils/inputs.ts:2160:10)
      at Object.applyInputs (src/utils/inputs.ts:2323:10)
      at Object.save (src/cache/index.ts:107:12)                                                  
      at Object.<anonymous> (src/cache/index.ts:137:13)                                                                                                                                              
      at fulfilled (src/cache/index.ts:3987:24)
```

If I update tsconfig.json to set `"target": "es2019"`, `ts-jest` throws a warning:

```
ts-jest[config] (WARN) There is a mismatch between your NodeJs version v10.18.0 and your TypeScript target es2019. 
This might lead to some unexpected errors when running tests with `ts-jest`. 
To fix this, you can check https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping
```

 and the tests still fail.

**Comment by brettdh** [comment]
Some orthogonal issues I noticed while testing this out:

1. `package-lock.json` is out of date. It seems like [renovatebot updated `@actions/cache`](https://github.com/ktmud/cached-dependencies/commit/2c24103d19e11f872572d251d9d0ae3a6446992a) to a newer commit in `package.json` without updating `package-lock.json`.
1. When I was testing locally using `npm install` instead of `npm ci`, I saw this test failure:
   ```
    FAIL  __tests__/cache.test.ts                                                                                                                                                                       
     ● Test suite failed to run                                                                      
                                                                                                                                                                                                     
    Cannot find module '@actions/http-client' from 'node_modules/@actions/cache/node_modules/@actions/cache/lib/internal/cacheHttpClient.js'
                                                                                                  
    Require stack:
      node_modules/@actions/cache/node_modules/@actions/cache/lib/internal/cacheHttpClient.js
      node_modules/@actions/cache/node_modules/@actions/cache/lib/cache.js
      node_modules/@actions/cache/src/save.ts
      src/cache/index.ts                                                                          
      __tests__/cache.test.ts                                                                     

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:308:11)         
      at Object.<anonymous> (node_modules/@actions/cache/node_modules/@actions/cache/src/internal/cacheHttpClient.ts:2:1) 
   ```

   which appeared to match the `package-lock.json` diff - the contents of `@actions/cache` that it locked somehow did not have `@actions/http-client` installed.

1. cached-dependencies uses `@zeit/ncc`, which is deprecated in favor of `@vercel/ncc`. I had to switch to the latter to test `--target`.

**Comment by ktmud** [comment]
Thanks for all the testing. Let me bump the other dependencies first.
